services:
  # Traefik - Reverse Proxy (SSL Reuse)
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      # SSL 설정 (DNS Challenge 사용)
      - --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL:-admin@example.com}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.letsencrypt.acme.keytype=EC256
      # HTTP redirect to HTTPS
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      # DNS Challenge (Cloudflare)
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53
      - --log.level=INFO
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker/traefik:/letsencrypt
      - ./docker/traefik/dynamic:/etc/traefik/dynamic:ro
    networks:
      - web

  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - web

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    networks:
      - web

  # Nextcloud
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    environment:
      # PHP 업로드 설정
      - PHP_UPLOAD_LIMIT=10G
      - PHP_MEMORY_LIMIT=512M
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
      - REDIS_HOST=redis
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER:-admin}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD:-changeme}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_DOMAIN:-localhost}
      - TRUSTED_PROXIES=172.16.0.0/12 10.0.0.0/8 192.168.0.0/16
      - OVERWRITEPROTOCOL=https
      - OVERWRITEHOST=${NEXTCLOUD_DOMAIN:-localhost}
      - OVERWRITEWEBROOT=
      - OVERWRITE_CLI_URL=https://${NEXTCLOUD_DOMAIN:-localhost}
    volumes:
      - ./data/nextcloud:/var/www/html
      - /mnt/storage:/var/www/html/data/insidewill/files/storage
      - /mnt/smb:/var/www/html/data/insidewill/files/smb
    labels:
      - "traefik.enable=true"
      # HTTP (redirect to HTTPS)
      - "traefik.http.routers.nextcloud.rule=Host(`${NEXTCLOUD_DOMAIN:-localhost}`)"
      - "traefik.http.routers.nextcloud.entrypoints=web"
      # HTTPS (use wildcard certificate)
      - "traefik.http.routers.nextcloud-secure.rule=Host(`${NEXTCLOUD_DOMAIN:-localhost}`)"
      - "traefik.http.routers.nextcloud-secure.entrypoints=websecure"
      - "traefik.http.routers.nextcloud-secure.tls=true"
      - "traefik.http.routers.nextcloud-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.nextcloud-secure.tls.domains[0].main=insidewill.site"
      - "traefik.http.routers.nextcloud-secure.tls.domains[0].sans=*.insidewill.site"
      # 보안 헤더 미들웨어 적용
      - "traefik.http.routers.nextcloud-secure.middlewares=nextcloud-redirectregex@docker,security-headers@file"
      # CalDAV/CardDAV redirects
      - "traefik.http.middlewares.nextcloud-redirectregex.redirectregex.permanent=true"
      - "traefik.http.middlewares.nextcloud-redirectregex.redirectregex.regex=https://(.*)/.well-known/(?:card|cal)dav"
      - "traefik.http.middlewares.nextcloud-redirectregex.redirectregex.replacement=https://$${1}/remote.php/dav"
    networks:
      - web
    depends_on:
      - postgres
      - redis

  super-rapidgator:
    build:
      context: /srv/app/super-rapidgator
      dockerfile: Dockerfile
    image: super-rapidgator:latest
    container_name: super-rapidgator
    restart: unless-stopped
    env_file: .env        # ⬅️ Redis URL, Rapidgator 인증 등
    environment:
      # 내부 서비스가 redis 컨테이너를 바라보도록
      - REDIS_URL=redis://redis:6379/0
      # FastAPI 기본 설정(필요 시)
      - HOST=0.0.0.0
      - PORT=8000
    depends_on:
      - redis
      - postgres          # 필요 없으면 제거
    networks:
      - web
    ports:
      - "8000:8000"
    volumes:
      - /mnt/smb/downloads:/app/downloads 
    # 포트 내보낼 필요 없음(프록시만 통과하면 됨)

  # --------------------------------------------------
  # Celery Worker
  # --------------------------------------------------
  celery:
    image: super-rapidgator:latest     # 앱 이미지 재사용
    container_name: super-rapidgator-worker
    restart: unless-stopped
    env_file: .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      # concurrency 조정
      - CELERY_CONCURRENCY=4
    command: >
      uv run celery
      -A src.super_rapidgator.workers.celery_app
      worker
      --loglevel=info
      --concurrency=${CELERY_CONCURRENCY:-4}
    depends_on:
      - redis
    networks:
      - web

networks:
  web:
    external: true 
