# 통합 서비스 Docker Compose 설정
# 실행: ./scripts/deploy.sh deploy
# 관리: ./scripts/deploy.sh [start|stop|restart|logs|status] [service|all]

services:
  # Traefik - Reverse Proxy & Load Balancer (임시 비활성화 - AIO 설정 완료 후 활성화)
  # traefik:
  #   image: traefik:v3.0
  #   container_name: traefik
  #   restart: unless-stopped
  #   command:
  #     - --api.insecure=true
  #     - --providers.docker=true
  #     - --providers.docker.exposedbydefault=false
  #     - --providers.file.directory=/dynamic
  #     - --providers.file.watch=true
  #     - --entrypoints.web.address=:80
  #     - --entrypoints.websecure.address=:443
  #     - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
  #     - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
  #     - --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL:-your-email@example.com}
  #     - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #     - "9090:8080"  # Traefik dashboard (포트 변경)
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - ./traefik:/letsencrypt
  #     - ./traefik/dynamic:/dynamic
  #   networks:
  #     - web

  # Nextcloud All-in-One Master Container
  nextcloud-aio:
    image: ghcr.io/nextcloud-releases/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer
    restart: unless-stopped
    ports:
      - "8080:8080"  # AIO 관리자 패널
      - "8443:8443"  # AIO HTTPS 인터페이스
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=0.0.0.0
      - SKIP_DOMAIN_VALIDATION=${SKIP_DOMAIN_VALIDATION:-false}
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web

networks:
  web:
    external: true

volumes:
  nextcloud_aio_mastercontainer: 