services:
  # Traefik - Reverse Proxy & Load Balancer
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/dynamic
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL:-your-email@example.com}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
      - "9090:8080"  # Traefik dashboard (포트 변경)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/letsencrypt
      - ./traefik/dynamic:/dynamic
    networks:
      - web

  # Nextcloud All-in-One Master Container
  nextcloud-aio:
    image: ghcr.io/nextcloud-releases/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer
    restart: unless-stopped
    ports:
      - "8080:8080"  # AIO 관리자 패널
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=0.0.0.0
      - SKIP_DOMAIN_VALIDATION=${SKIP_DOMAIN_VALIDATION:-false}
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web
    labels:
      - "traefik.enable=true"
      # AIO Interface (관리자 패널)
      - "traefik.http.routers.nextcloud-aio.rule=Host(`${NEXTCLOUD_DOMAIN}`) && PathPrefix(`/api/`)"
      - "traefik.http.routers.nextcloud-aio.entrypoints=websecure"
      - "traefik.http.routers.nextcloud-aio.tls.certresolver=letsencrypt"
      - "traefik.http.routers.nextcloud-aio.service=nextcloud-aio"
      - "traefik.http.services.nextcloud-aio.loadbalancer.server.port=8080"
      # Nextcloud 메인 앱
      - "traefik.http.routers.nextcloud.rule=Host(`${NEXTCLOUD_DOMAIN}`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls.certresolver=letsencrypt"
      - "traefik.http.routers.nextcloud.service=nextcloud"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=11000"

networks:
  web:
    external: true

volumes:
  nextcloud_aio_mastercontainer: 