version: '3.8'

services:
  samba:
    image: dperson/samba:latest
    container_name: samba
    restart: unless-stopped
    environment:
      - USER=${SAMBA_USER:-admin};${SAMBA_PASSWORD:-changeme}
      - SHARE=nas;/mnt/nas;yes;no;no;all;${SAMBA_USER:-admin}
      - WORKGROUP=${SAMBA_WORKGROUP:-WORKGROUP}
    volumes:
      - ../../nas:/mnt/nas
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139"
      - "445:445"
    networks:
      - backend

networks:
  backend:
    external: true 